### ISSUE TITLE
Deco X60 RSA key error when adding device

### ISSUE THREAD

**Issue by jonlanceley** [semihalev/com.tplink.router#1]
Hi 
I have a tp link Deco X60 and when adding the device i use the same ip and password as i would in the Deco web interface but get this error

Error getting rsa public key for password from TPLink

![Screenshot_20231224_061021_Homey](https://github.com/semihalev/com.tplink.router/assets/4244440/f1f30650-1434-43e5-96fd-ddb9d71ec471)

**Comment by semihalev** [comment]
Thank you for the report. I think the deco devices has different infrastructure. I will try find a deco device for test. I tested only with AX Archer routers.
