### ISSUE TITLE
Diagnostics report

### ISSUE THREAD

**Issue by Matthew1910** [semihalev/com.tplink.router#3]
221e7fdc-daa5-4c70-9159-ef79a02b9c8b

**Comment by semihalev** [comment]
I got the report. Looking Homey couldn't connect to your AX6000. Trying connect many times. Are there any limitations, restrictions or network issues between Homey and AX6000?

**Comment by Matthew1910** [comment]
> I got the report. Looking Homey couldn't connect to your AX6000. Trying connect many times. Are there any limitations, restrictions or network issues between Homey and AX6000?

Does not exist.  Homey is added to the router as a priority.

**Comment by Matthew1910** [comment]
Do you have any idea why the router won't connect?

**Comment by Matthew1910** [comment]
![Screenshot_20231225_123130_Homey.jpg](https://github.com/semihalev/com.tplink.router/assets/98472600/52140d43-584f-4416-a270-78e553d535f0)

**Comment by Matthew1910** [comment]
Everything works👍💪Problem with router settings

**Comment by semihalev** [comment]
Ohh! Great news. Have fun. 

Cheers.
