### ISSUE TITLE
Support for Omada devices please

### ISSUE THREAD

**Issue by heula** [semihalev/com.tplink.router#5]
Hi,

Is it possible to add support for Omada devices?
I have multiple access points Eap245, Eap 225, Eap110 en OC200 controller.
They can't be used in Homey 2023 now.
Also planning on buying some Omada Switches.

Thanks in advance.

**Comment by semihalev** [comment]
Hi,

The Omada cloud infrastructure completely different. Mostly Omada devices are using for small business or etc. I don't have any Omada device for test purposes. If I can find one, I can add definitely. 

Cheers.

**Comment by heula** [comment]
Hi Yasar,

Thanks for your fast response.
If you can find an Omada device or devices and can add it that would be
great but if not then no worries.

Thanks and have a nice day,

Regards,
Alex

Op za 13 jan 2024 om 16:11 schreef Yasar Alev ***@***.***>:
