### ISSUE TITLE
Archer AX55 used as a wireless accesspoint, but get an error when connecting it to Homey

### ISSUE THREAD

**Issue by khuizer** [semihalev/com.tplink.router#7]
When I add my Archer AX55, which I currently only use as an wifi access point, I am getting the following erorr. It looks like it kind of needs to have a ip address on the WAN port or something, which isn't connected, as it is only connected to the LAN, using one of the LAN ports.

Device Unavailable
Invalid capability (homey:app:com.tplink.router:wan_ipv4_ipaddr) value type. Expected: string. Got: undefined

Is there some way to get the device into Homey in a correct way?

**Comment by semihalev** [comment]
I solved this problem. I will release new version soon.

**Comment by khuizer** [comment]
Great, looking forward to it ;-)

**Comment by semihalev** [comment]
I released v1.0.8. Please update the app and try again.

**Comment by khuizer** [comment]
Yes, I updated the app and the device works now! Thanks!
